// <auto-generated />
namespace XZZ.Fk.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _834 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_834));
        
        string IMigrationMetadata.Id
        {
            get { return "201606240044059_834"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
